### ISSUE TITLE
upload files instead of directories

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/viewerjs#2]
It seems more natural to upload files rather than directories - is there any reason we do directories instead of file?

**Comment by jbernal0019** [comment]
Currently the Chrome browser is the only one that let users upload folders rather than individual files. We opted to upload folders because it allows to upload several DICOM series at the same time (each one in its own subfolder) and thus having several thumbnails in the thumbnails bar (one for each DICOM series).
